Ignore servers in serverlist that specify an invalid player count
XLabsProject/iw4x-client pull request #114
Opened 2021-08-20 16:54 UTC by Laupetin

Filter out any server that answer with a server info that specifies a player count that is greater than 18 or lower than 0.

2021-08-20 19:09 UTC, diamante0018 approved these changes
Tested it, it works.

2021-08-20 19:17 UTC, Rackover approved these changes
Very nitpicky: don't we have a macro for max player count?
Shouldn't we have one?

otherwise it's good, and can be merged as soon as you want to :)

2021-08-20 20:55 UTC, mjkzy requested changes

2021-08-20 20:55 UTC, mjkzy commented on src/Components/Modules/ServerList.cpp
> +				if(server.clients > 18 || server.maxClients > 18 || server.clients < 0 || server.maxClients < 0)
add space between ``if`` and the ``(``?

2021-08-20 22:16 UTC, Laupetin commented on src/Components/Modules/ServerList.cpp
> +				if(server.clients > 18 || server.maxClients > 18 || server.clients < 0 || server.maxClients < 0)
and i thought i was nitpicky lmao

2021-08-20 22:17 UTC, Laupetin commented
> Very nitpicky: don't we have a macro for max player count?
> Shouldn't we have one?
> 
> otherwise it's good, and can be merged as soon as you want to :)

Not macro. The game for sure has one the client doesn't though.

2021-08-21 10:07 UTC, Dss0 approved these changes

2021-08-21 10:07 UTC, merged