[Dvar] Use set raw method on dvars by default
XLabsProject/iw4x-client pull request #123
Opened 2021-08-29 15:45 UTC by diamante0018

Setraw functions have been removed of course

2021-09-01 17:53 UTC, Laupetin requested changes

2021-09-01 17:53 UTC, Laupetin commented on src/Game/Functions.cpp
> +	Copy_String_t Copy_String = Copy_String_t(0x4F3C80);
I think those are not needed since you dont use them

2021-09-01 17:53 UTC, Laupetin commented on src/Game/Structs.hpp
> +		DVAR_FLAG_UNKNOWN1800 = 0x1800,		//unknown
This is first of all not used and also not a flag but a combination of the flag values 0x1000 and 0x800

2021-09-01 17:53 UTC, Laupetin commented on src/Game/Functions.hpp
> +
Not used

2021-09-01 17:53 UTC, Laupetin commented on src/Game/Structs.hpp
> +	typedef enum : char
Didn't you want to change the dvar struct to use this enum then? Because what's the point of doing this is you are not making dvar_t::type this enum type

2021-09-01 17:53 UTC, Laupetin commented on src/Components/Modules/Dvar.cpp
> +		if (this->dvar && this->dvar->type == Game::dvar_type::DVAR_TYPE_BOOL)
i would add an assert here (before this line) that checks for the dvar type to not silently fail in debug mode. 
```cpp
assert(this->dvar->type == Game::DVAR_TYPE_BOOL);
```

2021-09-01 17:53 UTC, Laupetin commented on src/Components/Modules/Dvar.cpp
> +		if (this->dvar && this->dvar->type == Game::dvar_type::DVAR_TYPE_FLOAT)
I would add an assert here (see ``void Dvar::Var::set(bool enabled)``)

2021-09-01 17:53 UTC, Laupetin commented on src/Components/Modules/Dvar.cpp
> +		if (this->dvar && this->dvar->type == Game::dvar_type::DVAR_TYPE_INT)
I would add an assert here (see ``void Dvar::Var::set(bool enabled)``)

2021-09-01 17:53 UTC, Laupetin commented on src/Components/Modules/Dvar.cpp
> +		if (this->dvar && this->dvar->type == Game::dvar_type::DVAR_TYPE_STRING)
I would add an assert here (see ``void Dvar::Var::set(bool enabled)``)

2021-09-08 19:29 UTC, Laupetin approved these changes
looks fine. there might be a few high performant situations where you wouldn't necessarly want to use the game's Dvar_SetX functions because they convert the value into a string and then parse the string again but in the places that are effected by this PR there is no such case.

2021-09-08 19:29 UTC, Laupetin commented on src/Components/Modules/Dvar.cpp
> +	void Dvar::Var::set(bool enabled)
i mean since you keep bugging people because of code style: empty line between methods would be apprechiate. in reality i dont care though

2021-09-08 20:45 UTC, diamante0018 commented on src/Components/Modules/Dvar.cpp
> +	void Dvar::Var::set(bool enabled)
It wasn't me who bothered you for the space between if and ( 😂

2021-09-08 20:58 UTC, Dss0 approved these changes

2021-09-08 20:58 UTC, merged