Better r draw debug
XLabsProject/iw4x-client pull request #142
Opened 2021-11-08 16:59 UTC by Rackover

2021-11-09 11:51 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +	int drawDistance = 80000;
I think this could be a constexpr since it is only read from.

2021-11-09 11:51 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +					float rv = std::min((float)ent->handler, (float)5) / 5;
While you have a chance I would improve this code with something like
`float rv = std::min(static_cast<float>(ent->handler), 5.0f) / 5.0f;` and so on for the following expressions.

2021-11-09 11:51 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +		auto val = DrawModelNames.get<Game::dvar_t*>()->current.integer;
`DrawModelNames.get<int>()` Will do the same

2021-11-09 11:51 UTC, diamante0018 commented on src/Utils/Utils.cpp
> +	float Vec3SqrDistance(float(*v1)[3], float(*v2)[3])
I don't like the use of the pow. I think it is unnecessary and very slow.
I recall Laupetin saying that manually multiplying two values together is faster than using pow to the power of 2. 
If the exponent was larger than 2 then pow would be correct.

I would write this expression like this, making the parameters constant is not crucial.
```
float Vec3SqrDistance(const float v1[3], const float v2[3])
{
      return (v1[0]-v2[0])*(v1[0]-v2[0]) + (v1[1]-v2[1])*(v1[1]-v2[1]) * (v1[2]-v2[2])*(v1[2]-v2[2]);
}
```

2021-11-09 11:55 UTC, RektInator commented
Start using auto in your code.

2021-11-09 11:55 UTC, RektInator requested changes
Start using auto in your code.

2021-11-09 12:05 UTC, RektInator submitted a review, later dismissed

2021-11-09 12:05 UTC, RektInator commented on src/Components/Modules/Renderer.cpp
> +		float(*playerPosition)[3] = &clientEntity->r.currentOrigin;
???????

2021-11-09 12:05 UTC, RektInator commented on src/Components/Modules/Renderer.cpp
> +				const_cast<char*>("Disabled"),
Why are you allocating a vector for static data??????

2021-11-09 12:05 UTC, RektInator commented on src/Components/Modules/Renderer.cpp
> +		Scheduler::OnFrame([]() {
Wrong thread.

2021-11-09 12:05 UTC, RektInator commented on src/Components/Modules/Renderer.cpp
> +					auto b = scene->sceneModel[i].model->bounds;
Inconsistency is key.

2021-11-09 12:05 UTC, RektInator commented on src/Components/Modules/Renderer.cpp
> +		auto* scene = Game::scene;
WHY

2021-11-10 03:20 UTC, mjkzy commented
Um

2021-11-11 12:24 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +		auto val = DrawModelNames.get<Game::dvar_t*>()->current.integer;
Booleans are not great for storing a number from 0 to 4

2021-11-11 13:34 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			char* values[5] =
The array should be static. That is how the game does it.

2021-11-11 13:34 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			!Game::g_entities[clientNum].client) {
Perhaps this line could make use of the nullptr. Not really sure on this one

2021-11-11 13:34 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			!Game::g_entities[clientNum].client) {
Perhaps this line could make use of the nullptr. Not really sure on this one

2021-11-11 13:34 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +					auto gv = std::clamp(static_cast<float>(ent->handler - 5), 0.f, 5.f) / 5.f;
I am not sure if you meant to type `5.f` because in the line above you typed `5.0f`

2021-12-13 18:02 UTC, diamante0018 requested changes

2021-12-13 18:10 UTC, diamante0018 submitted a review, later dismissed

2021-12-16 22:41 UTC, Laupetin commented on src/Components/Modules/Renderer.cpp
> +		if (!r_drawSceneModelCollisions.get<bool>()) return;
This is registered as an enum but only used as a bool?

2021-12-16 22:41 UTC, Laupetin commented on src/Components/Modules/Renderer.cpp
> +		if (!r_drawSceneModelCollisions.get<bool>()) return;
Also i cant seem to make this do anything. Does this work?

2021-12-16 22:41 UTC, Laupetin commented on src/Components/Modules/Renderer.cpp
> +			Renderer::r_drawModelNames = Game::Dvar_RegisterEnum("r_drawModelNames", values, 0, Game::DVAR_FLAG_CHEAT, "Draw all model names");
Having this separate from r_drawModelBoundingBoxes with also an enum is kind of weird for me. I would have expected a bool for drawModelNames and the thing it draws being the same as r_drawModelBoundingBoxes

2021-12-16 22:41 UTC, Laupetin commented on src/Components/Modules/Renderer.cpp
> +		//Game::GfxWorld* gameWorld = *reinterpret_cast<Game::GfxWorld**>(0x66DEE94);
commented out code?

2021-12-17 08:46 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +		if (!r_drawSceneModelCollisions.get<bool>()) return;
It does, but not all maps have scene models, maybe it was the map?   i'm fixing the dvar type regardless, it might have been that

2021-12-17 08:48 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +			Renderer::r_drawModelNames = Game::Dvar_RegisterEnum("r_drawModelNames", values, 0, Game::DVAR_FLAG_CHEAT, "Draw all model names");
It's a valid point, i'm gonna think about it a little

2021-12-17 16:15 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +			Renderer::r_drawModelNames = Game::Dvar_RegisterEnum("r_drawModelNames", values, 0, Game::DVAR_FLAG_CHEAT, "Draw all model names");
I think I want to keep them separate for now because I use them for different purposes. Boundaries for collisions/boundaries/xmodel bugs and names to know the name of an xmodel in the world. Some areas have a lot of models and displaying both always could clutter the screen with information I don't want. So I think I'm going to keep it this way if that's ok for you 🙂

2021-12-17 16:47 UTC, Laupetin commented on src/Components/Modules/Renderer.cpp
> +			Renderer::r_drawModelNames = Game::Dvar_RegisterEnum("r_drawModelNames", values, 0, Game::DVAR_FLAG_CHEAT, "Draw all model names");
Alright

2021-12-17 16:47 UTC, Laupetin approved these changes

2021-12-17 17:02 UTC, merged