[Chat] Mute player (prevents them from using the chat)
XLabsProject/iw4x-client pull request #159
Opened 2022-01-01 21:37 UTC by diamante0018

This is a feature request by a staff member.

So allow me to briefly go other the design choice I made and why. This is a command that will most likely be used by IW4M via rcon. So I took into consideration that IW4M can manage the duration of a "mute" penalty on its own using a plugin.
Also if a player disconnects it can still be removed from the mute list. How? I used the GUID (named SteamId in the code) which is known to IW4M since it can parse it from the status command reply.

I decided to use the SteamID as a client identifier because IW4M can then unmute players even if they are offline. So mute penalties can stay persistent even if a player disconnects and then be lifted automatically. Imagine a situation where a player leaves the server and reconnects in an attempt to evade the ban (It's what happens in 4d1 client clones where they have InfinityScript), that should be taken care of.

Examples:
`muteClient <client number>` Adds the player to the mute list
`unmute <client number or the GUID>` or `unmute all`. Removes all clients or the specified client from the mute list.

2022-01-10 16:51 UTC, momo5502 requested changes

2022-01-10 16:51 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +	std::unordered_set<std::uint64_t> Chat::MuteList;
You should guard this variable with a mutex. It can be read/written to concurrently by different threads

2022-01-10 16:51 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +		if (Chat::MuteList.find(Game::svs_clients[player->s.number].steamID) != Chat::MuteList.end())
Mutex

2022-01-10 16:51 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +		if (Chat::MuteList.find(client->steamID) == Chat::MuteList.end())
Mutex

2022-01-10 16:51 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +		Chat::MuteList.erase(client->steamID);
Mutex

2022-01-10 19:00 UTC, diamante0018 commented on src/Components/Modules/Chat.cpp
> +	std::unordered_set<std::uint64_t> Chat::MuteList;
Thanks for the review. As I addressed it, I created a helper function to guard the list when it comes to the unmute command. Now all access is guarded by a mutex.
If you don't mind, please make sure the way I went about addressing your review is correct. Thanks.

2022-01-17 20:51 UTC, diamante0018 commented
Hi @momo5502 I addressed your review. Could you please make sure I got it right?
Thanks

2022-01-19 13:13 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +		std::lock_guard<std::mutex> _(Chat::AccessMutex);
You're locking this for the entire function. Even though this is not necessary

2022-01-19 13:13 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +		if (Chat::MuteList.find(Game::svs_clients[player->s.number].steamID) != Chat::MuteList.end())
I would use a unique lock before the if and unlock the lock inside the if and also outside, that way the lock is not helf for longer than needed, but also raii guarded

2022-01-19 13:13 UTC, momo5502 commented on src/Components/Modules/Chat.cpp
> +		if (Chat::MuteList.find(client->steamID) == Chat::MuteList.end())
Same here, unique lock and manual unlock as soon as not needed anymore

2022-02-14 07:12 UTC, momo5502 approved these changes

2022-02-14 15:41 UTC, merged