Refactor script related funcs/modules
XLabsProject/iw4x-client pull request #162
Opened 2022-01-07 21:14 UTC by diamante0018

Stuff that was modified:
- Use standard typedefs
- Remove checks that are not necessary. most removed one is if (client->state < 3) because it is wrong and is replaced by a check for the validity of the client pointer (gentity->client)
- Use scr_objecterror where appropiate
- Remove the spawn bot inner loop as it servers no benefits in my eyes (if you can't add a bot what makes you think trying again will work i.e. server might be full, not running or map rotating)
- removed what can only be described as a kek command ("NULL")
- use scr_objecterror instead of dropping (why would you want to drop the server for a simple gsc error?)
- function type declaration of some gsc functions

2022-01-23 12:11 UTC, Laupetin requested changes
At some places i didn't make any distinction between "your added code" and "code that was already like this before". Since you are refactoring i'm just commenting on anything that i noticed in the modules you touched.

2022-01-23 12:11 UTC, Laupetin commented on src/Components/Modules/Script.cpp
> +			Logger::Print(23, "%s\n", msg);
This logs a bunch of crap now when you compile as debug (`cannot set persistent data: developer_script must be false.`). Renders any other logging unnecessary. Can you maybe address this as well when you add this kind of logging capability :) Otherwise it's not really usable

2022-01-23 12:11 UTC, Laupetin commented on src/Components/Modules/Script.cpp
> +		assert(entref.entnum < Game::MAX_GENTITIES);
It does happen. When i do this without any entity to refer to:
```cpp
Notarget();
```
(instead of `self Notarget();`)
This needs to be handled in some way.

2022-01-23 15:26 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
> +					count = std::atoi(params->get(1));
You are right this functions lacks any sort of error reporting to the user

2022-01-23 15:45 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
> +			count = std::min(*Game::svs_numclients, count);
No, you can't overflow the server with bots.
SV_AddTestClient will return a nullptr if there are no more available slots in the server. The error is properly handled in the function 'Spawn'

2022-01-23 15:46 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  		Scheduler::OnFrame([]()
For the lack of a better scheduler, (that should be its own refactoring pr :) ) I will use the async scheduler pipeline

2022-01-23 15:50 UTC, Laupetin commented on src/Components/Modules/Bots.cpp
>  		Scheduler::OnFrame([]()
I commented towards the end of the source file what i would suggest is a better alternative. The async scheduler is not that much of an improvement really

2022-01-23 15:51 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  		Scheduler::OnFrame([]()
Sorry, I actually thought about this and I can't change it at the moment.
You are completely right but I don't want to break the bots, and I don't really wish to refactor the scheduler at the moment.
If I end up refactoring the scheduler to bring it up to speed with s1x I will definitely come back to this and use the correct scheduler pipeline.

2022-01-23 16:07 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  				rightInt = -127;
Good idea, actually I have no idea as to what these magic numbers are so I just ignore this code.

2022-01-23 16:12 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
> -			}
These checks have been superseded by the check inside the function Script::GetClientFromEnt

2022-01-23 16:17 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
> +			const auto* action = Game::Scr_GetString(0);
Right, will need to add checks

2022-01-23 16:18 UTC, Laupetin commented on src/Components/Modules/Bots.cpp
>  				rightInt = -127;
It's probably supposed to be INT8_MIN and INT8_MAX just that it's not actually INT8_MIN for some reason

2022-01-23 16:22 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  	} BotMovementInfo_t;
I mean the style of this project makes uses of unsigned __int16 more often than anything else so I mean when I make this sort of decisions I'm conflicted between using Microsoft unportable types or standard typedefs or well just unsigned short

2022-01-23 16:39 UTC, diamante0018 commented on src/Components/Modules/ClientCommand.cpp
> -			if (Game::Scr_GetNumParam() == 1u && Game::Scr_GetType(0) == Game::VAR_INTEGER)
`// gsc: Noclip(<optional int toggle>);` 
If there are no parameters it toggles automatically 
If there is one parameter it will use its value to determine whenever to enable or disable.

2022-01-23 16:40 UTC, Laupetin commented on src/Components/Modules/Bots.cpp
>  	} BotMovementInfo_t;
I mean the struct not the uint16_t :P

2022-01-23 16:41 UTC, Laupetin commented on src/Components/Modules/ClientCommand.cpp
> -			if (Game::Scr_GetNumParam() == 1u && Game::Scr_GetType(0) == Game::VAR_INTEGER)
Yes i know. You can give it more than 1 parameter and it does toggle again though which is what i mean...

2022-01-23 16:42 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
> +		assert(entref.entnum < Game::MAX_GENTITIES);
Odd, we know from very clean reversing that the game only has an assertion for this.
will remove assert and replace it with persistent check

2022-01-23 16:44 UTC, diamante0018 commented on src/Components/Modules/Client.cpp
>  		Client::AddFunctions();
Yes there is already some sort of ScriptStorage. 
As I don't feel like reworking the client module any time soon I'll either remove it at your request or leave it as it is.

2022-01-23 16:46 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
>  		return &Game::svs_clients[gentity->s.number];
if the clientptr is not null then we know it's a client therefore the entity belongs to a player and the number will be between 0-17. But I can add a check I guess not really necessary in my opinion

2022-01-23 16:56 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  				rightInt = -127;
Then wouldn't be better if I just cast the output of scr_getint to an int8_t

2022-01-23 16:57 UTC, Laupetin commented on src/Components/Modules/Script.cpp
>  		return &Game::svs_clients[gentity->s.number];
We already had this discussion... You are validating whatever you are using. Stop making assumptions and validating through them. I don't consider your guess "when there is a client pointer it is a valid ent number" proven nor is it helping in any way validating the data.
Check the value of the index you are accessing the array with if it is not 100% given that this is indeed a valid access. Everything else is overcomplicated, introduces a risk of being false and is simply impossible for any following coder to understand

2022-01-23 16:59 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  		{ "9",          33554432            },
Sorry where is +1 or +2?

2022-01-23 17:03 UTC, Laupetin commented on src/Components/Modules/Bots.cpp
>  				rightInt = -127;
No it would not be imo. For two reasons:
1. It's compiler implementation defined if that actually clamps or whether this actually just strips away any higher bits. So depending on the compiler this may do different things. It might work as expected with MSVC but it's not good coding style to do it that way.
2. You are making something that you want to do intentionally implicit. Code should reflect what you are trying to achieve with it. Indirectly doing this with a cast makes the code harder to understand because it is not directly obvious what you are trying to achieve with this. Just make it explicit with a clamp.

2022-01-23 17:10 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
>  			Game::Com_Printf(0, str);
Does this function even need to exist ? anyway will add checks

2022-01-23 17:10 UTC, Laupetin commented on src/Components/Modules/Bots.cpp
>  		{ "9",          33554432            },
Those were examples for the entries in this array. All of these entries with numbers as their string ("1", "2", "3", ... "9") are interpreted as possible commands given to the bot key function so `"+1"` `"-1"` `"+2"` `"-2"` .... `"+9"` `"-9"`.

Those are not actual commands though unlike the rest of the entries like `+reload` `-reload`. Idk what those numbers are supposed to be

2022-01-23 17:31 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
> +		const auto developer = Dvar::Var("developer").get<int>();
If I could I would make it behave like it did originally but I can't.
I mean the key difference here is basically either printing a small one-line message or a larger message.
I can speculate the reason as to why runtimeerrorinternal is not called if Game::scrVmPub->debugCode is true
is because they had the gsc debugger attached and that's where everything was displayed.
Because it is a contradiction that when we are developing we display less info to the console.
So actually I think that the best thing is to flip the conditional so that runtime error internal is called if we are developing and if are not it prints just one line of information

2022-01-23 17:39 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
> +			Logger::Print(23, "%s\n", msg);
Yeah I'll just redirect it to scr_errorinternal skipping the error printing

2022-01-23 17:56 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  		{ "9",          33554432            },
Me neither but yeah after it's not checked if input string is literal +7 or smth else It's actually forced to be it like that even thought it's not an action (??) I am really clueless.

2022-01-23 18:38 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
>  		return &Game::svs_clients[gentity->s.number];
Fine... The game only checks for that thought

2022-01-23 19:35 UTC, diamante0018 commented on src/Components/Modules/Bots.cpp
>  		Utils::Hook(0x627241, 0x4BB9B0, HOOK_CALL).install()->quick();
Brilliant solution. I will do that.

2022-01-24 02:48 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
> +			Logger::Print(23, "%s\n", msg);
I have no idea as to deal with this in a smart way.
On iw5 the function is `GScr_CheckAllowedToSetPersistentData` nullsubbed (calls to runtimeerror which is nullsubbed)
I will do the same I guess?

2022-01-24 03:24 UTC, diamante0018 commented
I sincerely hope I got everything @Laupetin.
I did more testing tonight with bot warfare mod and functionality did not break albeit it is now necessary to set sv_botWarfare dvar to true in order to disable test client functionality.
Other than that I hope the other commits I've done to address your review are correct.
Thanks again for your time

2022-01-24 03:40 UTC, diamante0018 commented on src/Components/Modules/Script.cpp
> +		const auto developer = Dvar::Var("developer").get<int>();
As that's done yes I do think who ever intends to debug gsc scripts should know what developer and developer_script are. Mind you that before my patch this was hardcoded to only print the simple 1 line of info to the console only on dedi. perhaps it could be an argument that in the modding guides provided by xlabs it should be mentioned what developer_script is for

2022-02-01 14:36 UTC, diamante0018 commented
I don't know what to do with the rest of the enum testClientKeyFlag enum (num_0 to num_9) is that also part of the usercmdButtonBits enum found in structs?

2022-02-14 18:28 UTC, diamante0018 commented
Recently tested and I can say that the current bot warfare release works without issue with the code I intent to merge with this pr.
Test clients fully work.
When a gsc function used by bw to move the bots is called test clients functionality is cut off until botstop gsc function is called. That will restore normal test client functionality provided the other bot gsc functions don't get called again.
By default test clients functionality is operational.

2022-03-07 22:52 UTC, diamante0018 commented
Ready to be reviewed. I promise not to push any more commits for at least 23 seconds

2022-04-09 17:48 UTC, Laupetin approved these changes

2022-04-09 17:48 UTC, merged