Add branding component
XLabsProject/iw4x-client pull request #219
Opened 2022-04-13 19:12 UTC by diamante0018

- Remove random profanity in the premake5. 
- 3 new dvars that control "development" branding-
- Move iw4x in menu (UI) branding to the top right corner of the screen (Conflict with development branding which has always been bottom right corner)
-

2022-04-13 19:36 UTC, diamante0018 commented
https://i.imgur.com/TLzOmH9.png

2022-05-07 11:05 UTC, Laupetin requested changes

2022-05-07 11:05 UTC, Laupetin commented on src/Components/Modules/Branding.cpp
> +	void Branding::Dvar_SetVersionString(const Game::dvar_t* dvar, const char* /*value*/)
[[maybe_unused]] if you wanna use it :P

2022-05-07 11:05 UTC, Laupetin commented on src/Components/Modules/Branding.cpp
> +		const auto height = Game::UI_TextHeight(font, fontScale);
Convert these two into float before using them otherwise it's undefined whether float + int is float or int

2022-05-07 13:31 UTC, diamante0018 commented on src/Components/Modules/Branding.cpp
> +	void Branding::Dvar_SetVersionString(const Game::dvar_t* dvar, const char* /*value*/)
You caught me red handed!

2022-05-07 14:29 UTC, Laupetin approved these changes

2022-05-07 14:29 UTC, Laupetin commented on src/Components/Modules/Branding.cpp
> +		auto* const font = Game::UI_GetFontHandle(placement, 0, 0.5f);
Is there a reason why this uses `0.5f` instead of `fontScale`?

2022-05-07 14:29 UTC, Laupetin commented on src/Components/Modules/Branding.cpp
> +		constexpr Game::vec4_t color = {0.4f, 0.69f, 1.0f, 0.69f};
The debug text you replaced does tint this green when a debugger is attached. Not super important but was a nice touch maybe you wanna do something like that too? :)

2022-05-07 14:43 UTC, diamante0018 commented on src/Components/Modules/Branding.cpp
> +		auto* const font = Game::UI_GetFontHandle(placement, 0, 0.5f);
Will change

2022-05-07 14:43 UTC, diamante0018 commented on src/Components/Modules/Branding.cpp
> +		constexpr Game::vec4_t color = {0.4f, 0.69f, 1.0f, 0.69f};
Not really a fan of that

2022-05-07 15:36 UTC, Laupetin approved these changes

2022-05-07 15:39 UTC, merged