Add RawMouse Compoment
XLabsProject/iw4x-client pull request #230
Opened 2022-04-29 14:31 UTC by GEEKiDoS

And enable dpi awareness for game window.
Should imporve mouse accuracy 

PS: should fixes mouse accelaction when mouse polling rate > 125Hz on iw6x/s1x (going to port this now

2022-04-29 16:45 UTC, diamante0018 requested changes
We are trying to use auto across new project's components and you should too for most local variable declarations like auto isclamped = true; etc...

2022-04-29 16:45 UTC, diamante0018 commented on src/Components/Loader.hpp
> +
Remove space

2022-04-29 16:45 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> +	int RawMouse::mouseRawY = 0;
Static class definitions have been traditionally been declared at the top of the cpp file (near dvar declaration)

2022-04-29 16:45 UTC, diamante0018 commented on src/Components/Modules/RawMouse.hpp
> +		static BOOL OnRawInput(LPARAM lParam, WPARAM);
We don't use c macros in the project. use regular bool if possible.

2022-04-29 16:45 UTC, diamante0018 commented on src/Game/Functions.hpp
> +	typedef void(*IN_RecenterMouse_t)();
__cdecl *. I know it's redundant but I'd like to keep consistency.

2022-04-29 16:45 UTC, diamante0018 commented on src/Components/Modules/Window.hpp
> +		typedef BOOL(WndProcCallback)(WPARAM wParam, LPARAM lParam);
why does the callback need to return a BOOL which is never used?

2022-04-29 16:45 UTC, diamante0018 commented on src/Components/Modules/Window.cpp
> +	void Window::EnableDpiAwareness()
Should add a check to see if you should call the actual function I think. Could also check the active pull request on the launcher that aims to fix a dpi related issue.
[launcher](https://github.com/XLabsProject/launcher/blob/develop/src/launcher/main.cpp#L45)

2022-04-29 16:51 UTC, diamante0018 requested changes

2022-04-29 16:51 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x475E65, RawMouse::IN_MouseMove, HOOK_JUMP).install()->quick();
Noticed this late sorry.
Use Hook::RedirectJump for this kind of hooking (jump). Other hooks are okay

2022-04-29 17:10 UTC, GEEKiDoS commented on src/Components/Modules/Window.hpp
> +		typedef BOOL(WndProcCallback)(WPARAM wParam, LPARAM lParam);
See https://github.com/XLabsProject/iw4x-client/pull/230/files/237a89fa710c721dba1ec801040134f7f3967a34#diff-33e2c4cabc153ecbcb147a717b0832c9a2646074838eb011c079a3c3faf00ddaR152

2022-04-29 17:16 UTC, diamante0018 commented on src/Components/Modules/Window.hpp
> +		typedef BOOL(WndProcCallback)(WPARAM wParam, LPARAM lParam);
My bad

2022-04-29 17:22 UTC, GEEKiDoS commented on src/Components/Modules/Window.cpp
> +	void Window::EnableDpiAwareness()
The Library::invokePascal already did the check stuff so I think it's just not needed

2022-04-29 17:34 UTC, GEEKiDoS commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x475E65, RawMouse::IN_MouseMove, HOOK_JUMP).install()->quick();
Hook::RedirectJump causes crash here, I think there's issue with Hook::RedirectJump?

2022-04-29 17:36 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x475E65, RawMouse::IN_MouseMove, HOOK_JUMP).install()->quick();
Oh wow that's terrible. Did not know that could happen. It's weird because it should be ideal for this kind of hook.

2022-04-29 17:41 UTC, GEEKiDoS commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x475E65, RawMouse::IN_MouseMove, HOOK_JUMP).install()->quick();
Hook::RedirectJump is for short jmp not for long jmp here I think, I'll keep the original code

2022-04-29 17:43 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> +		Utils::Hook(0x475E65, RawMouse::IN_MouseMove, HOOK_JUMP).install()->quick();
Yeah I looked at redirectjump code now. It does not overwrite the jump operand opcdode.

2022-04-29 17:49 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> -	Dvar::Var RawMouse::m_rawinput;
Sorry if I did not specify what is the naming convention.
There is a file in the root of the project directory of iw4x called CODESTYLE
Static class members should begin with an upper case letter.
For Dvars unfortunately it's a bit inconsistent across the project so I apologize if you got confused.
We usually keep the underscore for dvar/game variable/function names.
In this case: `M_RawInput` is correct just as `MRawInput`.

2022-04-29 18:00 UTC, GEEKiDoS commented on src/Components/Modules/RawMouse.cpp
> -	Dvar::Var RawMouse::m_rawinput;
Sorry, my bad. I see now

2022-04-29 18:02 UTC, GEEKiDoS commented on src/Components/Modules/RawMouse.hpp
> +		static int MouseRawX, MouseRawY;
Is it right now?

2022-04-29 18:03 UTC, diamante0018 commented on src/Components/Modules/RawMouse.hpp
> +		static int MouseRawX, MouseRawY;
Lovely

2022-05-02 19:14 UTC, Rackover reviewed
pretty cool!

2022-05-02 19:14 UTC, Rackover commented on src/Components/Modules/RawMouse.cpp
> +		static auto r_fullscreen = Dvar::Var("r_fullscreen");
this var can probably be fetched earlier and cached instead of fetched in every rawmousemove!

2022-05-02 19:21 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> +		static auto r_fullscreen = Dvar::Var("r_fullscreen");
There is the `static` keyword which has a very specific meaning when used inside a function. It's only fetched once.

2022-05-02 20:19 UTC, diamante0018 requested changes
I tested this in-game and I am happy with the changes you propose.
Could you address these last few requested changes I just made?
Then I think we are good to merge!
Thanks

2022-05-02 20:19 UTC, diamante0018 commented on src/Game/Structs.hpp
> +	};
static assert sizeof is 0x10 (16) please

2022-05-02 20:19 UTC, diamante0018 commented on src/Game/Functions.cpp
> +	WinVars_t* g_wv = reinterpret_cast<WinVars_t*>(0x64A3AC8);
I might be wrong but 0x64A3AC8 has no xrefs for me. Are you sure it's correct? Thanks for checking

2022-05-02 21:30 UTC, diamante0018 commented on src/Components/Modules/RawMouse.cpp
> +			RawMouse::M_RawInput = Dvar::Register<bool>("m_rawinput", true, Game::dvar_flag::DVAR_ARCHIVE, "Use raw mouse input, use in_restart to take effect if not enabled.");
Could you replace the dvar description with
`Use raw mouse input. Improves accuracy & has better support for higher polling rates.`
We had a discussion in the development channels and this seems to have been the best description in terms of ease of understanding from a user point of view.

2022-05-03 02:05 UTC, GEEKiDoS commented on src/Game/Functions.cpp
> +	WinVars_t* g_wv = reinterpret_cast<WinVars_t*>(0x64A3AC8);
It seems to be right, but seems like the game doesnt use anything other than hWnd and hInstance

2022-05-03 02:25 UTC, GEEKiDoS commented on src/Game/Functions.cpp
> +	WinVars_t* g_wv = reinterpret_cast<WinVars_t*>(0x64A3AC8);
I think I will just use Window::GetWindow() instead and remove this struct/g_wv

2022-05-03 08:27 UTC, diamante0018 approved these changes

2022-05-03 08:27 UTC, merged