Prefix custom GSC functions with "iw4x_"
XLabsProject/iw4x-client pull request #362
Opened 2022-07-17 08:34 UTC by Rackover

Now this is up for discussion - but the idea is to move our GSC functions to our own "namespace" to stop breaking half the mods in the planet that had a function called "god" or "ufo", and at the same time make mods a bit more futureproof (more easily identify which mods rely on iw4x and which don't, and not shit in the global GSC namespace in case other mw2 clients might want to use or might have used such named methods too, while not necessarily functioning the same). A bit like vendor prefixes for browsers?

I thought for a time about excluding bot commands from that restriction, not to break compatibility with previous versions of BotWarfare, but to be fair maybe it should be the other way around - and I'll PR botwarfare if this PR gets merged so it gets updated & functional as soon as possible 🙂

2022-07-17 16:09 UTC, Rackover commented
This PR includes deprecation warnings for some functions so that modders can have a bit of time to update their mods. In the meantime the mods will remain functionals, but warnings will show.
![image](https://user-images.githubusercontent.com/33836535/179410758-fe02ae13-7f8b-4c94-9169-16a6123eb085.png)
![image](https://user-images.githubusercontent.com/33836535/179410762-d05a6e2b-d092-4b5c-8ff9-6ac4878d13c0.png)

In the current state of the PR, BotWarfare 2.1.0 is fully functional - although it prints a few warnings upon compilation.

2022-07-17 16:53 UTC, diamante0018 requested changes

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +	std::unordered_set<std::string> Script::DeprecatedFunctionsAndMethods = {
Format

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +		std::string prefixedString = Utils::String::ToLower(addClientPrefix ? (Script::ClientPrefix + name).data() : name);
This is ugly to look at, mainly because of the .data() hack to make the ternary operator compile
```
std::string functionName= name;
if ( addClientPrefix )
{
    functionName.insert(0, Script::ClientPrefix)
}

Game::BuiltinFunctionDef toAdd;
...
CustomScrFunctions.insert_or_assign(Utils::String::ToLower(functionName), toAdd);

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
>  	{
same as above

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
>  	Game::BuiltinFunction Script::BuiltIn_GetFunctionStub(const char** pName, int* type)
format

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +		return Script::DeprecatedFunctionsAndMethods.find(name) != Script::DeprecatedFunctionsAndMethods.end();
https://en.cppreference.com/w/cpp/container/unordered_map/contains

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +			if (IsDeprecated(name)) {
format

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +				Toast::Show("cardicon_gumby", "WARNING!", Script::ScriptName + " uses the deprecated function " + name, 2048);
std::format()

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +				Logger::PrintError(Game::ERR_SCRIPT, "^1Attempted to execute deprecated builtin {} from {}! This method or function should be prefixed with 'iw4x_'. Automatically fixed the function for now, this
remove ^1 it's already in printerror

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +			if (IsDeprecated(name)) {
same comments as above

2022-07-17 16:53 UTC, diamante0018 commented on src/Components/Modules/UserInfo.cpp
> +		Script::AddMethod("ResetName", [](Game::scr_entref_t entref)  // gsc: self iw4x_ResetName()
rebase to origin/develop and add setclanname and resetclanname please

2022-07-17 17:25 UTC, diamante0018 requested changes

2022-07-17 17:25 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +	bool Script::IsDeprecated(const std::string& name) {
Format

2022-07-17 17:25 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +			std::string name = Utils::String::ToLower(*pName);
auto name = please

2022-07-17 17:25 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +			std::string name = Utils::String::ToLower(*pName);
auto name = please

2022-07-17 18:10 UTC, Laupetin commented on src/Components/Modules/GSC/Script.cpp
> +		toAdd.actionString = nullptr; // We don't need it
Might still be helpful for debugging messages the game outputs maybe? Is there any advantage of setting it to nullptr. You could also set it to the ptr from the std::string that is persisted in the CustomScrMethods map if you want it to have the prefix.

2022-07-17 18:10 UTC, Laupetin commented on src/Components/Modules/GSC/Script.cpp
> +				Logger::PrintError(Game::ERR_SCRIPT, "Attempted to execute deprecated builtin {} from {}! This function or method should be prefixed with 'iw4x_'. Automatically fixed the function for now, this w
I wouldn't tell the user it's "fixed for now" because they might think it doesn't matter and they don't care. Tell them what they need to do.

2022-07-17 18:10 UTC, Laupetin commented on src/Components/Modules/GSC/Script.hpp
> +		static std::string ClientPrefix;
can be constexpr instead of static, it won't change on runtime

2022-07-17 18:41 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.cpp
> +		toAdd.actionString = nullptr; // We don't need it
Unused. We call scr_registerfunction with the name from the map. The struct could be changed and we could use a custom one without actionstring

2022-07-17 20:33 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.hpp
> +		static std::string ClientPrefix;
a constexpr std::string? Why? It might make sense if it was a const char*, but in this case, it's useful if it stays a std::string.

2022-07-17 20:45 UTC, Laupetin commented on src/Components/Modules/GSC/Script.hpp
> +		static std::string ClientPrefix;
constexpr const char* --- nobody said it has to be std::string. Also even if you leave it as std::string you could make it const then

2022-07-17 21:10 UTC, diamante0018 commented on src/Components/Modules/GSC/Script.hpp
> +		static std::string ClientPrefix;
const std::string  sounds good.

2022-07-18 10:35 UTC, Rackover commented
Mods will not be able to support both iw4x versions (`if getdvar("version") == "x.x.x" {...} else {...}`) unfortunately due to the way GSC works (needs all function names to be resolved at compile time, no JIT), so they will have to update eventually once the grace period / deprecation period is over 🙂

2022-07-18 11:01 UTC, diamante0018 approved these changes

2022-07-18 11:01 UTC, merged