Json11 => NlohmannJson
XLabsProject/iw4x-client pull request #393
Opened 2022-07-28 09:51 UTC by Rackover

Removes json11 and uses nlohmann json instead (better support for unsigned types and other types)
API is almost the same, had to do a few changes here and there
Zonebuilder custom json material format has been removed since it's unused - no tools produce these materials anymore and ZB/I3X use dot iw4xmaterial binary format... for now!

Tried to build a map and it worked, played on it and it worked, but it could be good to test like Bans and Nodes and so so to make sure nothing has been butchered!

2022-07-28 09:57 UTC, diamante0018 commented on src/STDInclude.hpp
> +#endif
```cpp
#pragma warning(push)
#pragma warning(disable: 4100)
#include <json.hpp>
#pragma warning(pop)
``` 
I believe this should do it.

2022-07-28 09:58 UTC, diamante0018 commented on .gitmodules
> +
Please fix this too.

2022-07-28 09:58 UTC, Rackover commented on src/STDInclude.hpp
> +#endif
It's not a warning it's downright a compilation error

2022-07-28 10:17 UTC, diamante0018 commented on .gitmodules
> +
remove two new lines

2022-07-28 10:17 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +	void IMaterial::loadJson(Game::XAssetHeader* header, const std::string& name, Components::ZoneBuilder::Zone* /*builder*/)
`[[maybe_unused]] Components::ZoneBuilder::Zone* builder` please

2022-07-28 11:44 UTC, diamante0018 requested changes

2022-07-28 11:44 UTC, diamante0018 commented on src/Utils/Json.cpp
>  		default:
Use switch case fallthrough for null please
```
case nlohmann::json::value_t::null:
default:
              return "null";
              ```

2022-07-29 19:54 UTC, diamante0018 approved these changes

2022-07-29 19:54 UTC, merged