Adds a few gsc functions and methods
XLabsProject/iw4x-client pull request #40
Opened 2020-09-20 00:03 UTC by ineedbots

Added gsc functions:
  - GetSystemTime - returns the system time epoch in seconds
  - GetSystemMilliseconds - returns how many milliseconds has elapsed since the last second on the system
  - PrintConsole - prints to the console, since there is no way for scripts to display stuff to the console when 'developer 0'

Added gsc methods:
  - SetPing - sets (spoofs) the ping of a bot, since ping is always 999 for bots. This method needs to be called every frame (50ms) in script.

And when no 'bots.txt' file is found for custom bot names, it will use 'bot0', 'bot1', ... and so on. Rather than simply 'bot'.

2020-09-20 08:40 UTC, momo5502 commented
SetPing for bots? For real? What kind of whack shit is that 😂

2020-09-20 09:15 UTC, ineedbots commented
Yeah why not lol, I figured if they can have custom names, why not custom pings as well.

2020-09-21 16:35 UTC, Dss0 commented
what do you need the system time for?

2020-09-21 17:49 UTC, ineedbots commented
For the system timing, I found a use case for a server that wants to change it's settings for only one hour of an entire 24 hours. Or that you want to do something, like make a HTTP request, or flush something to a file every hour (or some timing independent of the engine's timing), etc.

The javelin bug is just toggled by a dvar that is set to false by default, so it won't be enabled unless a server wants it explicitly. This just gives a server the option to enable if they like, for a nostalgia trip or whatever.

2020-11-09 22:38 UTC, Dss0 requested changes
Executing commands on the (client) console can be used for malicious purposes. For example by shipping a config file that breaks the game with your mod and executing it. Also pretty much every function can be executed via gsc.

2020-11-09 22:46 UTC, Dss0 requested changes

2020-11-09 22:46 UTC, Dss0 commented on src/Components/Modules/Client.cpp
> +		Script::AddFunction("PrintConsole", [](Game::scr_entref_t) // gsc: PrintConsole(<string>)
This can be used to spam the client console with random text. Add a condition so that it only prints to the host's console.

2020-11-10 00:08 UTC, VVLNT commented on src/Components/Modules/Client.cpp
> +		Script::AddFunction("PrintConsole", [](Game::scr_entref_t) // gsc: PrintConsole(<string>)
> This can be used to spam the client console with random text. Add a condition so that it only prints to the host's console.

It _is_ only ran on the host.

> Executing commands on the (client) console can be used for malicious purposes. For example by shipping a config file that breaks the game with your mod and executing it. Also pretty much every function can be executed via gsc.

Same here. The commands are not ran by any client and Com_Printf is called by the host that is executing the GSC code, right? 🤔 To be fair, these functions probably shouldn't be put in module "Client".

2020-11-10 00:10 UTC, ineedbots commented on src/Components/Modules/Client.cpp
> +		Script::AddFunction("PrintConsole", [](Game::scr_entref_t) // gsc: PrintConsole(<string>)
Right, they should be moved into a different component.

2020-11-13 22:46 UTC, ineedbots commented
PR/branch got too many things in it, breaking up into separate branches

2020-11-13 22:46 UTC, closed without merging