Json materials
XLabsProject/iw4x-client pull request #427
Opened 2022-08-13 22:57 UTC by Rackover

Do not merge this, this needs massive cleanup before any merging is done. I'm just putting it here so I don't forget

Basically compatibility with iw3x shader porting + massive improvement on material/techset/technique formats (they are now readable, would you believe it)

+ a lot of duplicate, weird and useless stuff I need to get out.

2022-09-29 10:40 UTC, Rackover commented
Ready to review! (& merge?) (As soon as it builds....)

https://user-images.githubusercontent.com/33836535/193010585-b8b858ef-96bf-452a-aa05-495c9e9ca82e.mp4

2022-10-02 08:43 UTC, momo5502 commented on src/Components/Modules/AssetInterfaces/IFxWorld.cpp
> +		ZeroMemory(&map->glassSys, sizeof(Game::FxGlassSystem));
sizeof(map->glassSys)

2022-10-02 09:33 UTC, momo5502 commented on src/Components/Modules/AssetInterfaces/IGfxWorld.cpp
> +#define SWAP_GREEN_VEHICLE_XMODEL 1
Hm. i had that as well back when i developped it. a few models were causing extreme lag. reason was unknown to me. this workaround doesn't look nice, but i guess it's fine if that's currently the best option

2022-10-02 09:36 UTC, momo5502 commented on src/Components/Modules/AssetInterfaces/Isnd_alias_list_t.cpp
> +		Components::FileSystem::File aliasFile(Utils::String::VA("sounds/%s.json", name.c_str()));
i kinda like data more, tbh but whatever

2022-10-02 09:37 UTC, momo5502 approved these changes

2022-10-02 10:40 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/Isnd_alias_list_t.cpp
> +		Components::FileSystem::File aliasFile(Utils::String::VA("sounds/%s.json", name.c_str()));
The whole project uses data please go back to using it

2022-11-24 18:44 UTC, diamante0018 requested changes

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			auto gameWorldJson = nlohmann::json::parse(gameWorld.getBuffer());
unhandled exception

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
> +		try {
You will be banned for making this mistake!!!! 😢

2022-11-24 18:44 UTC, diamante0018 commented on src/Utils/Json.hpp
> +	unsigned long ReadFlags(const std::string binaryFlags, const size_t size);
consider using uint32_t

2022-11-24 18:44 UTC, diamante0018 commented on src/Utils/Compression.cpp
> +			auto compression = Z_BEST_COMPRESSION;
https://en.cppreference.com/w/cpp/language/constexpr

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +	void ZoneBuilder::ReallocateLoadedSounds(void*& data, [[maybe_unused]] void* a2)
I never understood with you have to write hooks like this, never done before and it doesn't make sense.

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		Game::MssSound* sound = Utils::Hook::Get<Game::MssSound*>(0x112AE04);
Why do you like typing twice? auto is your friend

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +	void ZoneBuilder::Zone::mapScriptString(unsigned short& gameIndex)
Don't know why it was changed.
Doesn't seem right

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
> +			techset = nlohmann::json::parse(tsFile.getBuffer());
😱

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +		auto materialJson = nlohmann::json::parse(materialInfo.getBuffer());
try/catch

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +		Components::FileSystem::File materialInfo(Utils::String::VA("materials/%s.iw4x.json", name.data()));
Better to use std::format where you can

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +		//// Match the name in case it's a known correspondance
Please consier removing unused uncommented code

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +				else {
😿

2022-11-24 18:44 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGfxWorld.cpp
> +					assert(model->model);
I would prefer you made the assertion before you assigned value to model->model

2022-11-24 18:55 UTC, diamante0018 commented
Solved merge conflicts, this still needs to be reviewed imo, many small details have not been noticed in the first review and I don't know if that was intentional or not.

2022-11-24 18:57 UTC, Rackover commented
It's not 100% ready anyway! Several display warnings need to be looked into

2022-11-24 19:16 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +									std::memcpy(asset->stateBitsEntry, header.material->stateBitsEntry, 48);
magic number 48?

2022-12-11 22:47 UTC, diamante0018 requested changes

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			auto gameWorldJson = nlohmann::json::parse(gameWorld.getBuffer());
unhandled exception!

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			Game::GameWorldMp* asset = builder->getAllocator()->allocate<Game::GameWorldMp>();
auto*

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			{
all of the following can throw if json is malformed

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			if (gameWorldJson["version"].get<int>() != IW4X_GAMEWORLD_VERSION)
is version an int or a string??

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +				Components::Logger::PrintError(Game::CON_CHANNEL_ERROR, "Invalid GameWorld json version for {}, expected {} and got {}\n", name, IW4X_GAMEWORLD_VERSION, gameWorldJson["version"].get<std::string>(
here it's a string?

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGfxWorld.cpp
> +					assert(model->model);
this still holds

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +#define IW4X_MAT_BIN_VERSION "1"
would make this an int if possible

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +		auto materialJson = nlohmann::json::parse(materialInfo.getBuffer());
exception here

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +		asset->info.name = builder->getAllocator()->duplicateString(materialJson["name"].get<std::string>());
throwing here if json is malformed

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +								reinterpret_cast<const char*>(wTerm64.data()),
would use utils::string::decode64 if possible

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +			nlohmann::json::array_t arr = materialJson["stateBitsTable"];
array instead of arr sounds more intutive

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +		//// Match the name in case it's a known correspondance
delete following code?

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +									std::memcpy(asset->stateBitsEntry, header.material->stateBitsEntry, 48);
^

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
> +		try {
please self review your code for styling mistakes like this

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
> +			techset = nlohmann::json::parse(tsFile.getBuffer());
exception here

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IXModel.cpp
> +
delete this spooky new line

2022-12-11 22:47 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +				if (type == Game::ASSET_TYPE_SOUND)
this is no bueno
if the type is not a sound return.

Do not nest your code into less readable stuff like this 😱

2022-12-11 22:47 UTC, diamante0018 commented on src/Game/Structs.hpp
> +  GfxSparkSurfIter sparkSurfIter;
oh god what happened here

2022-12-12 08:38 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IGfxWorld.cpp
> +					assert(model->model);
i don't see why! model->model will not be nullptr before the Find, but it might be after, and in that case we should assert & break because this will actually make the game crash

2022-12-12 08:39 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/ILoadedSound.cpp
> +				Utils::Stream::ClearPointer(&dest->sound.data);
There is something wrong here, potentially, as this version of zonebuilder has a lot of issues with sounds this has been changed (but it looks valid :(  )

2022-12-12 08:44 UTC, Rackover commented on src/Utils/Entities.cpp
> +					model != "com_plasticcase_green_big_us_dirt"s // Team zones
Double check because this should not be necessary

2022-12-13 21:29 UTC, Rackover commented on src/Utils/Json.hpp
> +	unsigned long ReadFlags(const std::string binaryFlags, const size_t size);
why?

2022-12-13 21:30 UTC, Rackover commented on src/Components/Modules/ZoneBuilder.cpp
> +	void ZoneBuilder::Zone::mapScriptString(unsigned short& gameIndex)
Its right

2022-12-13 21:31 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IMaterialTechniqueSet.cpp
> +			techset = nlohmann::json::parse(tsFile.getBuffer());
yea? its caught

2022-12-13 21:35 UTC, diamante0018 commented on src/Utils/Json.hpp
> +	unsigned long ReadFlags(const std::string binaryFlags, const size_t size);
I don't remember

2022-12-13 21:38 UTC, diamante0018 commented on src/Utils/Json.hpp
> +	unsigned long ReadFlags(const std::string binaryFlags, const size_t size);
It is a mistake to put const in the function definition in a header. it is simply ignored.

2022-12-13 21:40 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterialVertexDeclaration.cpp
> +				name, IW4X_TECHSET_VERSION, static_cast<int>(version));
this static cast is wrong

2022-12-13 21:41 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			if (gameWorldJson["version"].get<int>() != IW4X_GAMEWORLD_VERSION)
int, why ?

2022-12-13 21:43 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IGameWorldMp.cpp
> +			if (gameWorldJson["version"].get<int>() != IW4X_GAMEWORLD_VERSION)
two lines after you do `gameWorldJson["version"].get<std::string>()`
isn't that a mistake?
You probably mean to convert int to string first

2022-12-13 21:43 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +#define IW4X_MAT_BIN_VERSION "1"
not sure i can, this is backward compatibility stuff :v

2022-12-13 21:44 UTC, diamante0018 reviewed
undo changes to protobuf dependency

2022-12-13 21:46 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +								reinterpret_cast<const char*>(wTerm64.data()),
please do not suggest to me functions that don't exist on this project ♥

2022-12-13 21:50 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +								reinterpret_cast<const char*>(h064.data()),
reinterpret cast seems unecessary .data() already returns a const char*
https://en.cppreference.com/w/cpp/string/basic_string/data

2022-12-13 21:50 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterial.cpp
> +								reinterpret_cast<const char*>(wTerm64.data()),
reinterpret cast seems unecessary .data() already returns a const char*
https://en.cppreference.com/w/cpp/string/basic_string/data

2022-12-13 21:57 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			Renderer::r_forceTechnique = Game::Dvar_RegisterInt("r_forceTechnique", 0, 0, 14, Game::DVAR_NONE, "Forces a base technique on the renderer");
If you look at the dvar descriptions above they don't use the third person singular verb ending.
and neither do IW's dvar descriptions.

Remove the s from `Forces`

2022-12-13 21:58 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			Game::R_AddCmdDrawText(Utils::String::VA("%s", str.str().data()), std::numeric_limits<int>::max(), font, 15.0f, (height * scale + 1) * (i + 1) + 14.0f, scale, scale, 0.0f, color, Game::ITEM_TEXTST
`Utils::String::VA("%s", str.str().data())`
Please remove unnecessary VA.

2022-12-13 21:59 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			if (source->input.codeImages[i] == nullptr)
may i introduce you to the ternary operator??
color[0] = source->input.codeImages[i] == nullptr ? 1 : 0;

2022-12-13 21:59 UTC, diamante0018 commented on src/Components/Modules/Menus.cpp
>  	void Menus::RegisterCustomMenusHook()
remove unused function

2022-12-13 22:02 UTC, Rackover commented on src/Game/Structs.hpp
> +  GfxSparkSurfIter sparkSurfIter;
no idea this struct is really confusing and i'm not even sure this is the right one

2022-12-13 22:07 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +			Renderer::r_forceTechnique = Game::Dvar_RegisterInt("r_forceTechnique", 0, 0, 14, Game::DVAR_NONE, "Forces a base technique on the renderer");
This is extreme nitpicking

2022-12-13 22:13 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +			if (source->input.codeImages[i] == nullptr)
isn't there anything better to review in this 2500 lines PR ?? 
I won't introduce a ternary here, it is not worse nor better, it doesn't make the code more readable or less readable!

2022-12-13 22:27 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IMaterialVertexDeclaration.cpp
> +				name, IW4X_TECHSET_VERSION, static_cast<int>(version));
why ?

2022-12-13 23:11 UTC, diamante0018 commented on src/Game/Functions.cpp
> +	MaterialVertexShader*** varMaterialVertexShader = reinterpret_cast<MaterialVertexShader***>(0x112B338);
so this is a pointer to an array of MaterialVertexShader pointers?
please double check

2022-12-13 23:15 UTC, Rackover commented on src/Game/Functions.cpp
> +	MaterialVertexShader*** varMaterialVertexShader = reinterpret_cast<MaterialVertexShader***>(0x112B338);
this doesn't seem to be used anywhere actually... why is it here 🤔 gonna check in IDA
If i cant find an answer i'll just remove it

2022-12-13 23:17 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		auto allocatedSpace = Utils::Memory::AllocateArray<char>(length);
Isn't this a massive memory leak for each sound file, could you show me where you free your memory?

2022-12-13 23:20 UTC, diamante0018 commented on src/Components/Modules/AssetInterfaces/IMaterialVertexDeclaration.cpp
> +				name, IW4X_TECHSET_VERSION, static_cast<int>(version));
it's not needed

2022-12-13 23:22 UTC, Rackover commented on src/Components/Modules/ZoneBuilder.cpp
> +		auto allocatedSpace = Utils::Memory::AllocateArray<char>(length);
We don't, the goal is to keep them in memory! Because every sound we load is a sound we might want to write in a zone. fortunately the sounds are only loaded once but... yea when a zone is unloaded this memory ain't freed. when should I free it?
(imo it's not a big deal when zb leaks because it's only used to build one zone at a time... iw3x also has it. but i agree it doesnt look great)

2022-12-13 23:29 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IMaterialVertexDeclaration.cpp
> +				name, IW4X_TECHSET_VERSION, static_cast<int>(version));
You are sure that the "char" here will not become a unicode control character once in the log? Like \u0001 if it's version 1?  It will be turned into a solid 1 like an int would ?

2022-12-13 23:36 UTC, Rackover commented on src/Components/Modules/AssetInterfaces/IMaterialVertexDeclaration.cpp
> +				name, IW4X_TECHSET_VERSION, static_cast<int>(version));
tested it and you're right! damn i rembered adding this static cast because i had weird logs otherwise but i guess it must have been my imagination :o

2022-12-13 23:38 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		auto allocatedSpace = Utils::Memory::AllocateArray<char>(length);
Ah yes if this is zonebuilder only I guess it's not important

2022-12-13 23:39 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			if (source->input.codeImages[i] == nullptr)
The only thing it makes the code is less lengthy. I agree with "it doesn't make it more or less readable"

2022-12-14 08:25 UTC, diamante0018 submitted a review, later dismissed

2022-12-14 08:40 UTC, merged