Add cod4 map to dlc list (and absolutely nothing else)
XLabsProject/iw4x-client pull request #663
Opened 2022-12-23 20:18 UTC by Rackover

(The nothing else has been thoroughly tested)

2022-12-23 20:20 UTC, Rackover commented
https://user-images.githubusercontent.com/33836535/209402281-7b76fc7f-0101-4c6c-9d27-cdcacd1ddb11.mp4

2022-12-23 20:37 UTC, diamante0018 requested changes

2022-12-23 20:37 UTC, diamante0018 commented on src/Components/Modules/PlayerMovement.cpp
> +	void PlayerMovement::PM_playerTraceForLadder(Game::pmove_s* a1, Game::trace_t* results, const float* start, const float* end, Game::Bounds* bounds, int passEntityNum, int contentMask)
a1 -> pm

2022-12-23 20:37 UTC, diamante0018 commented on src/Components/Modules/PlayerMovement.hpp
> +		static void PM_playerTraceForLadder(Game::pmove_s* a1, Game::trace_t* results, const float* start, const float* end, Game::Bounds* bounds, int passEntityNum, int contentMask);
Same

2022-12-23 23:52 UTC, Rackover commented
shoutout to @GEEKiDoS  btw for the original idea!!

2022-12-24 20:16 UTC, diamante0018 commented on src/Components/Modules/PlayerMovement.cpp
> +#define SURF_LADDER 0x00000008
constexpr, this is a bad copy-paste from geekidos code.

2022-12-24 20:16 UTC, diamante0018 commented on src/Components/Modules/PlayerMovement.cpp
> +		Utils::Hook::Call<void(Game::pmove_s*, Game::trace_t*, const float*, const float*, Game::Bounds*, int, int)>(0X458980)(pm, results, start, end, bounds, passEntityNum, contentMask);
already present in functions.cpp

2022-12-24 20:16 UTC, diamante0018 approved these changes

2022-12-24 20:17 UTC, diamante0018 approved these changes

2022-12-24 20:23 UTC, merged