IW4Of Fixes
XLabsProject/iw4x-client pull request #775
Opened 2023-02-15 22:32 UTC by Rackover

Some stuff we forgot or messed up

2023-02-15 22:32 UTC, Rackover commented
Still not building valid zones btw so wait a bit before merging, it's not over

2023-02-15 22:34 UTC, diamante0018 requested changes

2023-02-15 22:34 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		if (Game::fs_basepath && Game::fs_gameDirVar)
this is wrong it should be *fs_basepath && *fs_gameDirVar
the type of this variable is ** (double pointer) so this if statement is never false

2023-02-16 18:26 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		this->branding = {this->zoneName.data(), 0, static_cast<int>(dataLen), data.data()};
pretty sure UAF for data, have you tested this?

2023-02-16 18:27 UTC, Rackover commented on src/Components/Modules/ZoneBuilder.cpp
> +		this->branding = {this->zoneName.data(), 0, static_cast<int>(dataLen), data.data()};
Not yet this is a WIP, i have bigger problem right now with remappedtechinquesets not being saved properly, I'll come back to this before this PR is ready :)

2023-02-16 18:36 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		this->branding = {this->zoneName.data(), 0, static_cast<int>(dataLen), data.data()};
Okay, I'll mark this as "request changes" if I can so it does not go unforgotten. this becomes a nulltpr after the function exits.

2023-02-16 18:42 UTC, diamante0018 commented on src/Components/Modules/Maps.cpp
> +	int16 Maps::CM_TriggerModelBounds(unsigned int triggerIndex, Game::Bounds* bounds) {
Please fix the braces and rename function to contain the word Stub or Hk or Hook

2023-02-16 18:52 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		std::string data = std::format("Built using the IW4x ZoneBuilder! {:%d-%m-%Y %H:%M:%OS}", now);
TBH I didn't know this was possible but I tested it and it works.
Example output: `Built using the IW4x ZoneBuilder! 16-02-2023 18:51:33`
Just use auto please.

2023-02-16 19:24 UTC, Rackover commented on src/Components/Modules/ZoneBuilder.cpp
> +		std::string data = std::format("Built using the IW4x ZoneBuilder! {:%d-%m-%Y %H:%M:%OS}", now);
Ok so no need to fix UAF or anything ?

2023-02-16 19:33 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		std::string data = std::format("Built using the IW4x ZoneBuilder! {:%d-%m-%Y %H:%M:%OS}", now);
What? This is unrelated

2023-02-16 19:33 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		std::string data = std::format("Built using the IW4x ZoneBuilder! {:%d-%m-%Y %H:%M:%OS}", now);
UAF is still present a couple of lines after this

2023-02-16 19:56 UTC, Rackover commented on src/Components/Modules/ZoneBuilder.cpp
> +		std::string data = std::format("Built using the IW4x ZoneBuilder! {:%d-%m-%Y %H:%M:%OS}", now);
Did not know what you were talking about with "i tested it and it works"

2023-02-16 20:35 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +		std::string data = std::format("Built using the IW4x ZoneBuilder! {:%d-%m-%Y %H:%M:%OS}", now);
My bad. What I meant to say is that I didn't know you could format the time like that. But yeah the UAF is present.
🅱️

2023-02-17 09:59 UTC, Rackover commented
This is ready as far as i'm concerned, builds maps properly

2023-02-17 11:13 UTC, diamante0018 submitted a review, later dismissed

2023-02-17 11:22 UTC, diamante0018 approved these changes

2023-02-17 11:26 UTC, merged