Small thing
XLabsProject/iw4x-client pull request #799
Opened 2023-02-27 22:02 UTC by Rackover

2023-02-27 22:12 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
I don't know about this one to be honest.

2023-02-27 22:13 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
It's already there actually

2023-02-28 14:58 UTC, diamante0018 requested changes

2023-02-28 14:58 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +		if (r_listSamplers.get<bool>())
Should return here.

2023-02-28 14:58 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +			float color[4] = { 0.0f, 1.0f, 0.0f, 1.0f };
Unnecessary code change by adding space after { }

2023-02-28 14:58 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
Could you try to do without?

2023-02-28 15:00 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
without the stringstream you mean? you sure it would be faster without?

2023-02-28 15:03 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
We never use it for string formatting, it should be possible to simply use one std::format.
...Or not?

2023-02-28 15:06 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
i once again do not understand what you're talking about. Do you not want to use it because "we never use it" or do you have an actual reason why stringstream would be bad in the current situation ?

2023-02-28 15:06 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
performance wise concatenating strings would be way worse, what are your alternatives & why are you looking for one .?

2023-02-28 15:12 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +				std::stringstream str;
Why are you brining up string concatenation?
Since you have std::format available can't you use one format string and pass the different things as arguments of std::format. That is what I intended the first time.

2023-03-05 19:45 UTC, diamante0018 approved these changes

2023-03-05 19:53 UTC, merged