A pot pourris of cleanup and feeder repurposing
XLabsProject/iw4x-client pull request #814
Opened 2023-03-06 22:12 UTC by Rackover

Preparation for the IW5 DLC update.
You may comment but you may not touch !

2023-03-15 18:18 UTC, diamante0018 commented on src/Components/Modules/FastFiles.cpp
> +		Scheduler::Once([]()
https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/Scheduler.cpp#L135

2023-03-15 18:19 UTC, Rackover commented on src/Components/Modules/FastFiles.cpp
> +		Scheduler::Once([]()
i think this is not what i want

2023-03-15 18:27 UTC, diamante0018 commented on src/Components/Modules/FastFiles.cpp
> +		Scheduler::Once([]()
I thought otherwise, it seems to be almost identical to your function. Could you please try to use it and see if it works?

2023-03-16 12:47 UTC, diamante0018 requested changes

2023-03-16 12:47 UTC, diamante0018 commented on src/Utils/Thread.cpp
> -
I do not approve of the removal of this for no reason whatsoever.

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/Zones.cpp
> +		if (ZoneBuilder::IsEnabled())
Fix the formatting of this file.

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +				for (auto entry : list)
use reference, `auto& entry`

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/ZoneBuilder.cpp
> +				for (auto entry : fileList)
use reference, `auto& entry`

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/UIFeeder.cpp
> -			UIMapName = Dvar::Register<const char*>("ui_map_name", "mp_afghan", Game::DVAR_NONE, "");
Why did you remove the default vaue?

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/UIFeeder.cpp
> +			Dvar::Var("ui_mapname").set(mapname);
dvar already defined here.
https://github.com/XLabsProject/iw4x-client/blob/develop/src/Game/Dvars.cpp#L86

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/UIFeeder.cpp
> +			UIMapName.set(Game::SEH_StringEd_GetString(mapName.data()));
Why are you using this instead of https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/Localization.hpp#L12

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/UIFeeder.cpp
> +#if DEBUG
Wrong! Use `#ifdef` for checking if a macro exists.

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/Renderer.cpp
> +	Dvar::Var Renderer::r_drawLights;
Why is this changed mixed with an IW5 DLC Prep PR? Put it in another PR please.

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/ArenaLength.cpp
> +		Utils::Hook::Set<char**>(0x4A95F0 + 3, &ArenaLength::NewArenaInfos[0]);
Simplify with just writing `ArenaLength::NewArenaInfos` instead of & and [0]

2023-03-16 12:47 UTC, diamante0018 commented on src/Components/Modules/Maps.cpp
> +	std::mutex Maps::CustomMapsScanningMutex;
For what reason is there a mutex? Does seem like there is one? Where is the multithreading in this code?

2023-03-16 12:50 UTC, Rackover commented on src/Components/Modules/UIFeeder.cpp
> -			UIMapName = Dvar::Register<const char*>("ui_map_name", "mp_afghan", Game::DVAR_NONE, "");
Cause Afghan is not a usermap . The whole purpose of this feeder has changed.
The default value is not necessary anymore anyway

2023-03-16 12:55 UTC, Rackover commented on src/Components/Modules/Renderer.cpp
> +	Dvar::Var Renderer::r_drawLights;
It's not the only cleanup thing here. There's also the techset dump thing that was superseeded by iw5of, among other things. 
I saw you change some completely unrelated menufiles on the IW5 menu PR to remove a checkClass call, oddly enough it did not strike you as out-of-place enough to warrant a new PR. I'm sure you'll be able to mentally accommodate that this change will cause no harm in this PR, just like the dumptechset one or the checkclass one.

2023-03-16 12:55 UTC, diamante0018 commented on src/Components/Modules/Maps.cpp
> +	std::mutex Maps::CustomMapsScanningMutex;
Yes.

2023-03-16 12:55 UTC, diamante0018 commented on src/Utils/Thread.cpp
> -
Nope, it's you who has to elaborate as to why you want to remove this, not me.
The code can stay.

2023-03-16 13:16 UTC, Rackover commented on src/Utils/Thread.cpp
> -
It's deadcode

2023-03-16 18:33 UTC, Rackover commented on src/Components/Modules/UIFeeder.cpp
> +			UIMapName.set(Game::SEH_StringEd_GetString(mapName.data()));
It's older code, did not know about Localization

2023-03-16 18:34 UTC, Rackover commented on src/Components/Modules/UIFeeder.cpp
> +#if DEBUG
i know it's used that way throughout the iw4x codebase so i'll modify it to match, but still this sounds really dumb to me. `DEBUG false` should not trigger the debug blocks. We should use #if instead of #ifdef for these throughout the codebase...

2023-03-16 19:03 UTC, diamante0018 commented on src/Components/Modules/FastFiles.cpp
> +		g_loadingInitialZones = Dvar::Register("g_loadingInitialZones", true, 0, "Is still loading initial zones");
`Dvar::Register<bool>` to respect the template argument defined here: https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/Dvar.hpp#L37

2023-03-16 19:06 UTC, diamante0018 commented on src/Components/Modules/Maps.cpp
> +		return Utils::String::VA("usermaps/%s/%s.arena", mapName.data(), mapName.data());
since the return type is std::string std::format should be used

2023-03-16 19:07 UTC, diamante0018 commented on src/Components/Modules/Maps.cpp
> +					Components::Logger::Print("Discovered custom map {}\n", zoneName);
Remove Components:: as this is already inside said the namespace

2023-03-16 19:07 UTC, diamante0018 commented on src/Components/Modules/Maps.cpp
> +			std::string arena = GetArenaPath(mapname);
const auto is preferred

2023-03-17 09:26 UTC, Rackover commented on src/Components/Modules/Zones.cpp
> -		returnSafe:
i formatted the whole file like you asked :(

2023-03-17 09:29 UTC, Rackover commented on src/Components/Modules/ArenaLength.cpp
> +		Utils::Hook::Set<BYTE>(0x4A95F8, sizeof(Game::newMapArena_t::mapName));
In the general case I would agree with you, however in that specific case this is writing the size of the string to pass it to Info_ValueForKey so imo using the sizeof makes more sense (it's used as a string of constant size, not as an array, even though the difference is purely semantic). Ill add ARRAYSIZE to please you but wrong move imo

2023-03-17 09:31 UTC, Rackover commented on src/Components/Modules/Zones.cpp
> +			// Change stream for images
Okay, I addressed your review and gave you write access on the branch, don't fuck it up 🙋‍♀️

2023-03-17 12:26 UTC, diamante0018 submitted a review, later dismissed

2023-03-17 12:39 UTC, diamante0018 approved these changes

2023-03-17 12:46 UTC, merged