Skip specops entities
XLabsProject/iw4x-client pull request #92
Opened 2021-07-04 22:30 UTC by Rackover

CODO has additional specops entities that mw2 doesn't know how to manage, which adds weird hitboxes on some multiplayer maps. This code prevents them from loading... but i'm not really satisfied with it.
would love to get some input on it

2021-07-05 11:21 UTC, diamante0018 commented on src/Components/Modules/QuickPatch.cpp
> +				if (isSpecOps && isSpecOpsOnly) {
Format here is off

2021-07-05 11:21 UTC, diamante0018 commented on src/Components/Modules/QuickPatch.cpp
> +		return Utils::Hook::Call<bool(char*)>(0x444810)(a1);
Can't you do it yourself here instead of calling the game function e.g
`  return !strncmp(a1,"dyn_",4); `
I mean, since you are already hooking the function call, I am simply wondering if it's better to do it like you are doing or call strncmp yourself here. It would not change the code functionality but perhaps it might improve readability since it's not obvious what the function at 0x444810 does (unless you open game binary with ida). Replacing it with `return !strncmp(a1,"dyn_",4);` would make it apparent.

2021-07-05 11:21 UTC, diamante0018 commented on src/Components/Modules/QuickPatch.cpp
> +	bool QuickPatch::IsDynClassnameStub(char* a1) {
format

2021-07-05 15:05 UTC, Laupetin requested changes
Didn't test the chances for whether they work but if you say they do for your maps then its fine to merge after these few clearity and format things have been addressed. Besides that good pr.
(I know is poorly documented at a lot of places already but that can be addressed in new changes at least)

2021-07-05 15:05 UTC, Laupetin commented on src/Components/Modules/QuickPatch.cpp
> +				bool isSpecOpsOnly = *val == 49; // 49 => Ascii "1"
Also this only checks if the value *starts with* a 1 character. Practically will work but you could just as well also check for the zero byte for completion sake and to show that it is your intention to check for "1" explicitly.
So when you're at it just do `val[0] == '1' && val[1] == '\0';`

2021-07-05 15:17 UTC, Rackover commented on src/Components/Modules/QuickPatch.cpp
> +				bool isSpecOps = strncmp(key, "script_specialops", 16) == 0;
i do not know how to count

2021-07-05 19:25 UTC, Rackover commented
I updated the PR according to your comments, but I think there's still one thing missing - this code should only execute on 460+ CODO maps, but if I check Zone::Version it's always wrong the first time (but correct when I map restart) due to being set too late (i suppose?). This would probably need addressing otherwise the loading of _any_ map will be slowed down during entity spawning

2021-07-28 19:42 UTC, Laupetin approved these changes

2021-07-28 21:18 UTC, Dss0 approved these changes

2021-07-28 21:18 UTC, merged